<a href="https://colab.research.google.com/github/Nischal5123/foreCache-interaction/blob/develop/StateActionProbab_ROI_Subset_Statistics_Mann_Kendall_Trend_ForeCache.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
from statsmodels.tsa.stattools import adfuller
import pymannkendall as mk

In [ ]:
pip install pymannkendall

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# this is implemented from STATE ACTION ANALYSIS FILE : https://colab.research.google.com/drive/1n9nJdd84etLey3piTKkRJmttpZlW1gor#scrollTo=bgGiHn-LobHm

#GET ALL STATE ACTION MODEL FOR NDSI 2D AND NDSI 3D
global_drive_path="/content/drive/MyDrive/ForeCache/interactions/stateActionModel/"
path=(str(global_drive_path) +"/ndsi-3d")
fileNames_NDSI_3D=[]
for filename in os.listdir(path):
    if filename.endswith(".csv"):
        filePath=(os.path.join(path, filename))
        fileNames_NDSI_3D.append(filename)
    else:
        continue
path=(str(global_drive_path) +"/ndsi-2d")
fileNames_NDSI_2D=[]
for filename in os.listdir(path):
    if filename.endswith(".csv"):
        filePath=(os.path.join(path, filename))
        fileNames_NDSI_2D.append(filename)
    else:
        continue
matchingName=[]
df_twoD=[]
df_threeD=[]
path_twoD=(str(global_drive_path) +"/ndsi-2d")
path_threeD=(str(global_drive_path) +"/ndsi-3d")
for i in range(len(fileNames_NDSI_2D)):
  for j in range(len(fileNames_NDSI_3D)):
  # if fileNames_NDSI_2D[i].removesuffix('taskname_ndsi-2d-task_') == fileNames_NDSI_3D[i].removesuffix('taskname_ndsi-3d-task_'):
   if fileNames_NDSI_2D[i][22:] == fileNames_NDSI_3D[j][22:]:
      #print(os.path.join(path, str(fileNames_NDSI_2D[i])))
      df=pd.read_csv(os.path.join(path_twoD, str(fileNames_NDSI_2D[i])),sep=',')
      df_twoD.append(df)
      df=pd.read_csv(os.path.join(path_threeD, str(fileNames_NDSI_3D[j])),sep=',')
      df_threeD.append(df)
      matchingName.append(fileNames_NDSI_2D[i])
#STORE ALL USERS NAME
users=[]
for name in matchingName:
    users.append(name[22:-4:1])

In [ ]:
class StationarityTests:
    def __init__(self, significance=.05):
        self.SignificanceLevel = significance
        self.pValue = None
        self.isStationary = None
        self.trend= None

    def ADF_Stationarity_Test(self, timeseries, printResults = True):
      #Dickey-Fuller test:
      adfTest = adfuller(timeseries, autolag='AIC')
      
      self.pValue = adfTest[1]
      
      if (self.pValue<self.SignificanceLevel):
          self.isStationary = True
      else:
          self.isStationary = False
      
      if printResults:
          dfResults = pd.Series(adfTest[0:4], index=['ADF Test Statistic','P-Value','# Lags Used','# Observations Used'])
          #Add Critical Values
          for key,value in adfTest[4].items():
              dfResults['Critical Value (%s)'%key] = value
          print('Augmented Dickey-Fuller Test Results:')
          print(dfResults)
    
    def Mann_Kendall_Stationarity_Test(self, timeseries, printResults = True):
      #Mann Kendall Trend Test:
      mktTest = mk.original_test(timeseries)
      
      self.pValue = mktTest[2]
      self.trend= mktTest[0]
      self.isStationary = mktTest[1]
      
      if printResults:
          dfResults = pd.Series(mktTest[0:3], index=['Trend Type','Stationarity','P-Value'])
          #Add Critical Values
          for key,value in mktTest[3].items():
              dfResults['Critical Value (%s)'%key] = value
          print('Mann Kendall Trend Test:')
          print(dfResults)

In [ ]:
def make_numerical_dataframe(df):
  df['State_Action']=(df['Action']+ df['State'])
 
  df['Action']=pd.factorize(df['Action'])[0]
  df['State']=pd.factorize(df['State'])[0]
  state_action_correlated_series=pd.factorize(df['State_Action'])[0]
 
  action_only_series=df['Action'].values
  state_only_series=df['State'].values
  options=[state_action_correlated_series,action_only_series,state_only_series]
  return options

In [ ]:

#3D Mann Kendall
def Subset_screenshot_time(user,all_states_dataframe):
  failed_files=[]
  final_dataframe_3d = pd.DataFrame(columns=['User','StateNumber','Subtask_ROI','MKT Stationary_State_Action'])
  for i in tqdm(range(len(all_states_dataframe))):
    subtask=0
    length_parsedFile=0
    print("For state: ############",i)

    window_dataframe=all_states_dataframe[i]

    subtask_values=window_dataframe["Subtask_ROI"].unique()
    print(subtask_values)
    original_fileLength=len(window_dataframe)

    while ((length_parsedFile < original_fileLength) and (subtask <= len(subtask_values))):
      
      window_dataframe_subset=window_dataframe.loc[window_dataframe['Subtask_ROI'] == subtask_values[subtask]]
      length_parsedFile+=len(window_dataframe_subset)
      #print("Length of file",len(window_dataframe_subset), " in ","Subtask: ",subtask_values[subtask])
      #creating series
      state_action_correlated_series=window_dataframe_subset['StateActionProbab'].values

      three_series=[state_action_correlated_series]
      three_series_results=[user,i,subtask_values[subtask]]
      for series in (three_series):
        if len(series)>2:
          sTest_state = StationarityTests()
          sTest_state.Mann_Kendall_Stationarity_Test(series, printResults = False)
          three_series_results.append(sTest_state.trend)
          
        else:
          three_series_results.append("Not Enough Data")
          failed_files.append(user)
      #adding results per subtask per user to dataframe
      df_length = len(final_dataframe_3d)
      final_dataframe_3d.loc[df_length] = three_series_results
      subtask +=1
  return final_dataframe_3d
    

In [ ]:
#3D Mann Kendall
saveDir=(str(global_drive_path) +"StationarityTests/ndsi-3d/ActionBased")
combined_final_dataframe_3d = pd.DataFrame(columns=['User','StateNumber','Subtask_ROI','MKT Stationary_State_Action'])
array_of_dataframes=[]
for j in tqdm(range(len(df_threeD))):
  
  all_states_dataframes=[]
  # df_Navigation=df_threeD[j].loc[df_threeD[j]['State'] == 'Navigation']
  # all_states_dataframes.append(df_Navigation)
  df_Sensemaking=df_threeD[j].loc[df_threeD[j]['State'] == 'Sensemaking']
  all_states_dataframes.append(df_Sensemaking)
  # df_Answering=df_threeD[j].loc[df_threeD[j]['State'] == 'Answering']
  # all_states_dataframes.append(df_Answering)
  df_Foraging=df_threeD[j].loc[df_threeD[j]['State'] == 'Foraging']
  all_states_dataframes.append(df_Foraging)
  print(j)
  print(users[j])
  #running MKT on one user after dividing data based on states
  if (len(all_states_dataframes) == 2):
    actiondf=Subset_screenshot_time(users[j],all_states_dataframes)
    array_of_dataframes.append(actiondf)
    
  else:
    print("failed for user", user[j])
array_of_dataframes = pd.concat(array_of_dataframes)
userfilename= "All Users_ScreenShot_MKT_sliding_.xlsx"
array_of_dataframes.to_excel(os.path.join(saveDir,userfilename), index=False)
   

In [ ]:

#2D Mann Kendall
def Subset_screenshot_time(user,all_states_dataframe):
  failed_files=[]
  final_dataframe_2d = pd.DataFrame(columns=['User','StateNumber','Subtask_ROI','MKT Stationary_State_Action'])
  for i in tqdm(range(len(all_states_dataframe))):
    subtask=0
    length_parsedFile=0
    print("For state: ############",i)

    window_dataframe=all_states_dataframe[i]

    subtask_values=window_dataframe["Subtask_ROI"].unique()
    print(subtask_values)
    original_fileLength=len(window_dataframe)

    while ((length_parsedFile < original_fileLength) and (subtask <= len(subtask_values))):
      
      window_dataframe_subset=window_dataframe.loc[window_dataframe['Subtask_ROI'] == subtask_values[subtask]]
      length_parsedFile+=len(window_dataframe_subset)
      #print("Length of file",len(window_dataframe_subset), " in ","Subtask: ",subtask_values[subtask])
      #creating series
      state_action_correlated_series=window_dataframe_subset['StateActionProbab'].values

      three_series=[state_action_correlated_series]
      three_series_results=[user,i,subtask_values[subtask]]
      for series in (three_series):
        if len(series)>2:
          sTest_state = StationarityTests()
          sTest_state.Mann_Kendall_Stationarity_Test(series, printResults = False)
          three_series_results.append(sTest_state.trend)
          
        else:
          three_series_results.append("Not Enough Data")
          failed_files.append(user)
      #adding results per subtask per user to dataframe
      df_length = len(final_dataframe_2d)
      final_dataframe_2d.loc[df_length] = three_series_results
      subtask +=1
  return final_dataframe_2d
    

In [ ]:
#2D Mann Kendall
saveDir=(str(global_drive_path) +"StationarityTests/ndsi-2d/ActionBased")
combined_final_dataframe_3d = pd.DataFrame(columns=['User','StateNumber','Subtask_ROI','MKT Stationary_State_Action'])
array_of_dataframes=[]
for j in tqdm(range(len(df_threeD))):
  
  all_states_dataframes=[]
  df_Navigation=df_twoD[j].loc[df_twoD[j]['State'] == 'Navigation']
  all_states_dataframes.append(df_Navigation)
  df_Sensemaking=df_twoD[j].loc[df_twoD[j]['State'] == 'Sensemaking']
  all_states_dataframes.append(df_Sensemaking)
  df_Answering=df_twoD[j].loc[df_twoD[j]['State'] == 'Answering']
  all_states_dataframes.append(df_Answering)
  df_Foraging=df_twoD[j].loc[df_twoD[j]['State'] == 'Foraging']
  all_states_dataframes.append(df_Foraging)
  print(j)
  print(users[j])
  #running MKT on one user after dividing data based on states
  if (len(all_states_dataframes) == 4):
    actiondf=Subset_screenshot_time(users[j],all_states_dataframes)
    array_of_dataframes.append(actiondf)
    
  else:
    print("failed for user", user[j])
array_of_dataframes = pd.concat(array_of_dataframes)
userfilename= "All_Users_ScreenShot_MKT_sliding_.xlsx"
array_of_dataframes.to_excel(os.path.join(saveDir,userfilename), index=False)
   

  0%|          | 0/19 [00:00<?, ?it/s]

0
userid_82316e37-1117-4663-84b4-ddb6455c83b2



  5%|▌         | 1/19 [00:00<00:02,  6.51it/s]

For state: ############ 0
[1 2 3]
For state: ############ 1
[1 2 3]
For state: ############ 2
[]
For state: ############ 3
[1 2 3]
1
userid_d6555293-35c7-4c27-b522-38d67d2d1b1a



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3]
For state: ############ 1
[1 2 3]
For state: ############ 2
[]
For state: ############ 3
[1 2 3]


100%|██████████| 4/4 [00:00<00:00, 71.87it/s]

2
userid_bda49380-37ad-41c5-a109-7fa198a7691a




 16%|█▌        | 3/19 [00:00<00:01,  9.68it/s]

For state: ############ 0
[1 2 3 4]
For state: ############ 1
[1 2 3 4]
For state: ############ 2
[]
For state: ############ 3
[1 2 3 4]
3
userid_da52acdd-3cea-483c-86e5-2c2740d371aa



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3 4 5]
For state: ############ 1
[1 2 3 4]

100%|██████████| 4/4 [00:00<00:00, 56.09it/s]



For state: ############ 2
[]
For state: ############ 3
[1 2 3 5]
4
userid_3abeecbe-327a-441e-be2a-0dd3763c1d45



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1]
For state: ############ 1
[1 2 3]


 26%|██▋       | 5/19 [00:00<00:01, 10.92it/s]

For state: ############ 2
[]
For state: ############ 3
[1]
5
userid_ac5b65d7-f260-4534-9fae-d998b726ed32



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3]
For state: ############ 1
[1 2 3]
For state: ############ 2
[1]
For state: ############ 3
[1 2 3]


100%|██████████| 4/4 [00:00<00:00, 44.92it/s]


6
userid_ff56863b-0710-4a58-ad22-4bf2889c9bc0



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3]
For state: ############ 1
[1 2 3]
For state: ############

 37%|███▋      | 7/19 [00:00<00:01, 10.01it/s]

 2
[]
For state: ############ 3
[1 2 3]
7
userid_bc9f9425-e867-4876-a5d9-791229916767



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 3 4]
For state: ############ 1
[1 2 3]
For state: ############ 2
[4]
For state: ############ 3
[1 3 4]


100%|██████████| 4/4 [00:00<00:00, 46.04it/s]


8
userid_8bf5b71b-dfd4-403f-8791-06427b26ccaf



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3]
For state: ############ 1
[1 2 3]


 47%|████▋     | 9/19 [00:00<00:01,  9.74it/s]

For state: ############ 2
[]
For state: ############ 3
[1 2 3]
9
userid_7d014c75-453b-4188-9e4e-fb086984896a



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3]
For state: ############ 1
[1 2 3 4]


 53%|█████▎    | 10/19 [00:01<00:00,  9.68it/s]

For state: ############ 2
[]
For state: ############ 3
[1 2 3]
10
userid_6d49fab8-273b-4a91-948b-ecd14556b049



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3 4]
For state: ############ 1
[1 2 3]



100%|██████████| 4/4 [00:00<00:00, 37.61it/s]

For state: ############ 2
[1]
For state: ############ 3
[1 2 3 4]


 58%|█████▊    | 11/19 [00:01<00:00,  8.70it/s]

11
userid_733a1ac5-0b01-485e-9b29-ac33932aa240



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 3]


100%|██████████| 4/4 [00:00<00:00, 57.01it/s]

For state: ############ 1
[1 2 3]
For state: ############ 2
[]
For state: ############ 3
[1 3]


12
userid_954edb7c-4eae-47ab-9338-5c5c7eccac2d



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3 4]


 68%|██████▊   | 13/19 [00:01<00:00,  9.10it/s]

For state: ############ 1
[1 2 3 4]
For state: ############ 2
[]
For state: ############ 3
[1 2 3 4]
13
userid_cd3ef507-e3e9-4edb-9222-90a69a9bf272



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3]
For state: ############ 1
[1 2 3]
For state: ############ 2
[]
For state: ############ 3
[1 2 3]


 74%|███████▎  | 14/19 [00:01<00:00,  9.09it/s]

14
userid_44968286-f204-4ad6-a9b5-d95b38e97866



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 4]


100%|██████████| 4/4 [00:00<00:00, 56.66it/s]


For state: ############ 1
[1 2 3]
For state: ############ 2
[]
For state: ############ 3
[1 2 4]
15
userid_8b544d24-3274-4bb0-9719-fd2bccc87b02



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3 4]
For state: ############ 1
[1 3 4]
For state: ############ 2
[1 4]
For state: ############ 3
[1 2 4]


 84%|████████▍ | 16/19 [00:01<00:00,  9.10it/s]

16
userid_e4221e48-0930-40db-af3c-f4de1ed87582



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 3 4]
For state: ############ 1
[1 2 3 4]
For state: ############ 2
[4]
For state: ############ 3
[1 3 4]


 89%|████████▉ | 17/19 [00:01<00:00,  8.90it/s]

17
userid_a6aab5f5-fdb6-41df-9fc6-221d70f8c6e8



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3]
For state: ############ 1
[1 2 3]
For state: ############ 2
[]
For state: ############ 3
[1 2 3]


 95%|█████████▍| 18/19 [00:01<00:00,  9.03it/s]

18
userid_93be0a02-3f7a-46c9-b526-aa956ed00856



  0%|          | 0/4 [00:00<?, ?it/s]

For state: ############ 0
[1 2 3]
For state: ############ 1
[1 2 3]
For state: ############ 2
[]
For state: ############ 3
[1 2 3]


100%|██████████| 19/19 [00:02<00:00,  9.22it/s]
